# Disable dbus
context.properties = {
    support.dbus = false
}

# Add dummy sink
context.objects = [
    {   factory = adapter
        args = {
           factory.name     = support.null-audio-sink
           node.name        = "virtual-sink"
           media.class      = Audio/Sink
           object.linger    = true
           audio.position   = [ FL FR ]
          #  monitor.channel-volumes = true
          #  monitor.passthrough = true
        }
    }
]
