# Disable Dbus loading for pipewire
context.properties = {
    support.dbus = false
}

wireplumber.settings = {
    device.routes.default-sink-volume = 1.0
}

wireplumber.profiles = {
    main = {
        support.dbus = disabled
        hardware.bluetooth = disabled
        hardware.video-capture = disabled
    }
}